### ISSUE TITLE
[Bug] StreamDiffusion_Loader and StreamDiffusion_Sampler nodes show red when loaded workflow from Readme.

### ISSUE THREAD

**Issue by ricardofeynman** [jesenzhang/ComfyUI_StreamDiffusion#2]
When I load the workflow both StreamDiffusion_Loader and StreamDiffusion_Sampler nodes are in red, and when I search for StreamDiffusion_Loader to manually replace, that node isn't availble. No obvious error thrown in the terminal. 

StreamDiffusion_Sampler can be searched for without issue.

Looking forward to testing this out, thanks for releasing.

Edit: The issue persisted after several restarts, no errors thrown, however after updating another custom node and reloading, the issue seems to have resolved itself. No clues as to what was the cause unfortunately.

**Comment by YacratesWyh** [comment]
How did you solve this? I still have this problem

**Comment by ricardofeynman** [comment]
> after updating another custom node and reloading, the issue seems to have resolved itself. _No clues as to what was the cause unfortunately._

Sorry, there was no clear solution in my case. Try restarting the server, the machine, try reinstalling the node, try updating something. For me it involved enabling a disabled node then I did a fetch update through manager. After that restart, the workflow loaded up fine, no red nodes, no missing node when searching. Weird.
