### ISSUE TITLE
1.Sloved Import failed Error  2. Isn't switch button enable？  

### ISSUE THREAD

**Issue by Erwin11** [jesenzhang/ComfyUI_StreamDiffusion#7]
### Section1.To Slove Import failed Error,

step-1: Open this folder:
custom_nodes\ComfyUI_StreamDiffusion， 
![image](https://github.com/jesenzhang/ComfyUI_StreamDiffusion/assets/6300501/cdd6936e-31d5-4306-8e98-6ad61571d259)

step-2: type CMD in the address , enter.

step-3: in CMD, type it.
```
 ..\..\..\python_embeded\python.exe -s -m pip install diffusers==0.25.0
```
enter.

step-4: Restart ComfyUI.

### Section2. Isn't switch buttion enable？  
![image](https://github.com/jesenzhang/ComfyUI_StreamDiffusion/assets/6300501/42dddd4a-4aac-4436-a4a2-867d65e649eb)
This Warning is confusing.

**Comment by jesenzhang** [comment]
The warning message is about the scheduler, the attribute will work when the scheduler has the attribute. You can read more from https://huggingface.co/docs/diffusers/v0.9.0/en/api/schedulers.
